### PR TITLE
Code: Fixes Microsoft Edge detection.

### PR DESCRIPTION
**Pull request by am11**
Issue-URL: #79.

### CODE REVIEW

**Comment by am11** [comment]
@jdalton, FYI: on probing the `platform` object with this delta, here is the result of `JSON.stringify(platform)` on my system:

```json
{
  "description":"Microsoft Edge 12.10240 on Windows NT 10.0 64-bit",
  "layout":"Trident",
  "manufacturer":null,
  "name":"Microsoft Edge",
  "prerelease":null,
  "product":null,
  "ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240",
  "version":"12.10240",
  "os":{
    "architecture":64,
    "family":"Windows NT",
    "version":"10.0"
  }
}
```

and the output of `platform.toString()`:

```
Microsoft Edge 12.10240 on Windows NT 10.0 64-bit 
```

**Comment by d10** [comment]
LGTM.

**Comment by testower** [comment]
Any idea when this will be merged?

**Comment by jdalton** [comment]
@d10 is lead, its up to him.

**Comment by testower** [comment]
Judging from his last comment he seems happy to get this merged. Do you have merge permissions @jdalton?

**Comment by jdalton** [comment]
Yap :D

**Comment by am11** [comment]
@jdalton, @mathiasbynens, if I understood it correctly, was this fix replaced by scooter plugin in downstream? Unfortunately Edge is still recognized incorrectly. We get this message on Windows 10 Edge browser: `Browserscope thinks you are using Chrome 52.0.2743`. Could you please tell me which repo should I attempt to re-fix this issue? The disambiguation fix here still works for me locally on the latest version of Edge.

IMO, this is a high-risk issue: JSPerf stats are getting mangled where Edge performs poorly and in some cases (like branch-prediction algorithm improvements in Chakra), Chrome is stealing credit due for Edge.

**Pull request merged**
