### PR TITLE
Add Edge Anaheim detection

### PR DESCRIPTION
**Pull request by fdellwing**
Microsoft once again wants to annoy all developers...

See https://github.com/matomo-org/device-detector/pull/5943 for details.

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @fdellwing!

We'll wait for the official UA string to be published by MS.

**Comment by fdellwing** [comment]
Fine for me, I needed to patch this into our local version to handle the preview browsers we have.

**Comment by fdellwing** [comment]
The first official builds for Win10 are published: https://www.microsoftedgeinsider.com/

**Comment by jdalton** [comment]
Thanks @fdellwing!

**Pull request merged**
