### PR TITLE
Fix #132 - Add Chrome Headless detection

### LINKED ISSUE #132: Headless Chorme is detected as Safari
UA string: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/60.0.3107.4 Safari/537.36

Result of parse() is:

```javascript
{
  description: 'Safari 7.x on Linux 64-bit',
  layout: 'WebKit',
  manufacturer: null,
  name: 'Safari',
  prerelease: null,
  product: null,
  ua: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/60.0.3107.4 Safari/537.36',
  version: '7.x',
  os: {
    architecture: 64,
    family: 'Linux',
    version: null,
  },
}
```

Tracked down because [wdio-visual-regression-service] uses this library to detect the browser name, and it ends up as `Safari`.

[wdio-visual-regression-service]: https://github.com/zinserjan/wdio-visual-regression-service

### PR DESCRIPTION
**Pull request by chiefcll**
Add Chrome Headless support as Chrome browser to keep it simple
for others to see as Chrome per Issue #127.

### CODE REVIEW

**Comment by jdalton** [comment]
Thank you @chiefcll!

**Comment by chiefcll** [comment]
Thank you! - This is becoming more important with Chrome Headless playing a much larger role in CI systems.

**Comment by bnjmnt4n** [comment]
Thanks for the PR! I've only recently gotten back into open source, and will be looking at these commits later this week. What do you think about marking Chrome Headless differently from Chrome though? Should there be a `platform.headless` option in v2 for Chrome Headless, Phantomjs, and others? Looking for any opinions!

**Comment by chiefcll** [comment]
I originally had the platform.name as 'Chrome Headless' but then changed it to Chrome due to seeing issue #127 - It might be better to have a `platform.type` which would then be `mobile` or `headless`. I'm not sure how many differences there are between Chrome + Headless + mobile as far as rendering and JS engine.

**Comment by omnibs** [comment]
Is any missing work preventing this from getting merged? I'd be happy to help.

**Comment by kevinpthorne** [comment]
bumping

**Comment by bnjmnt4n** [comment]
Hi all, sorry for the delay, working on merging some of the open PRs and releasing a new version soon. No firm promises, but expect a new version by the end of next week.

**Pull request closed without merging**
