### PR TITLE
Version number in file (#121)

### PR DESCRIPTION
**Pull request by ohpe**

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks ohpe! This leaves a place that often gets overlooked. If there was a way to generate it on npm publish that would be preferred.

**Comment by ohpe** [comment]
@jdalton I'm not sure it's possible to do using npm publish. I'll double check.

**Comment by ohpe** [comment]
@jdalton updated the PR. It should work on `npm publish`

**Comment by ohpe** [comment]
up :)

**Comment by jdalton** [comment]
Ok, if you rebase again I'll merge. Thanks for this!

**Comment by ohpe** [comment]
It should be ok now.

**Comment by jdalton** [comment]
Thanks!

**Pull request merged**
