### PR TITLE
device Archos 40 Cesium detects as iPhone iOS

### PR DESCRIPTION
**Pull request by BdR76**
I tested platform.js on several devices and found that a device called Archos 40 Cesium, running Windows Phone 8.1, is incorrectly detected as iPhone iOS 7.0.3.

I've fixed this by adding 'Archos' to the arrays passed to getProduct and getManufacturer, and the os and device are then detected correctly.

Note: I've also added the device types 'Cesium' and 'Helium' although I don't know how this is supposed to work exactly.

### CODE REVIEW

**Comment by jdalton** [comment]
Is there a way to fix it without adding a new device?

**Comment by BdR76** [comment]
Maybe there's a way to do it without adding a new device. The bug happens because the useragent string contains "like iPhone" (btw the same thing happens in the useragent of the Lumia device).

So in the getProduct it _could_ be fixed by adding a RegExp to excluding product preceded by "like". I can't create such a RegExp but besides that it's very messy imho, it would only further complicate things.

**Comment by BdR76** [comment]
Btw this issue is similar to this older issue about detecting the Nokia Lumia -> https://github.com/bestiejs/platform.js/issues/71

**Comment by BdR76** [comment]
There are many Windows Phone devices (like HTC, Huawei Ascend, Acer Liquid) and instead of including them all, I think the text part "like iPhone" should be totally ignored.

Maybe the useragent string should be modified at the start. The useragent could be stripped of some misleading "red herring" strings. so just remove "like iPhone" and similarly the phrases "like Mac OS X;" and "like Mac OS X)" could also be ignored.

**Pull request closed without merging**
