### PR TITLE
UCBrowser Support

### PR DESCRIPTION
**Pull request by varshneygaurav**
Support for UCBrowser has been added.

Refrence: http://www.webapps-online.com/online-tools/user-agent-strings/dv/browser212364/uc-browser

### CODE REVIEW

**Comment by jdalton** [comment]
Could you flatten these commits.

**Comment by varshneygaurav** [comment]
OK

**Comment by varshneygaurav** [comment]
Self Abandoned for flatting commits.

**Comment by jdalton** [comment]
For future reference you can flatten commits without closing a PR by simply rebasing, squashing them, and then force pushing to update the PR.

**Comment by varshneygaurav** [comment]
Thanks for your valuable suggestion. i will do the same in my next contribution.

**Pull request closed without merging**
